name: Generate Snake

on:
  schedule:
    - cron: "0 3 * * *"  # 매일 새벽 3시 (UTC 기준, 한국시간 오전 12시)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: HONGHONGPYO
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
